curve:
  # Fineness of the curve
  fineness: 5
  # Maximum length a curve can be built
  max-set-length: 1024
  # If this value is true, the center will be thicker
  thicken-center: false

particles:
  pos:
    # Particle color
    color:
      pos: 0x00FFFF
      start_pos: 0xFF00FF
      end_pos: 0xFFFF00
      f: 0xFF0077
      b: 0x7700FF

    # Particle density per block
    density: 4

  line:
    # Particle density per block
    density: 4
    # Maximum length to display particles
    max-length: 512

# Message file path
message-file: "%datafolder%/messages/en.yml"