name: CurveBuilding
version: '${version}'
description: A plugin to build curves.
author: kous500
main: me.kous500.curvebuilding.bukkit.CurveBuildingPlugin
depend: [WorldEdit]

commands:
  /bc:
    description: Make the Bezier curve.
    permission: CurveBuilding.bc
    permission-message: You do not have <permission>.
    usage: |
      /<command> [-options] [n] [m]
      Example: /<command> -a - Replace only air blocks with the curve.
      Example: /<command> -x - Read the region in X-direction.
      Example: /<command> -z - Read the region in Z-direction.
      Example: /<command> n
      Example: /<command> n m
      n: Input a integral number or 0.
      Set the plane every n blocks the curve goes.
      m: Input a integral number or 0.
      Set the plane after m blocks the curve goes.
  /pos:
    description: Set your pos.
    permission: CurveBuilding.pos
    permission-message: You do not have <permission>.
    usage: |
      Example: /<command> clear <posType> - Delete the specified connection or control point.
      Example: /<command> Delete all connection and control points.
      Example: /<command> set <posType> - Sets a connection point at your current position.

permissions:
  CurveBuilding.*:
    description: Gives access to all worldeditExtension commands.
    default: op
    children:
      CurveBuilding.bc: true
      CurveBuilding.pos: true
  CurveBuilding.bc:
    description: Gives access to bc commands.
  CurveBuilding.pos:
    description: Gives access to pos commands.